name: "Alexa Audio Bridge"
description: "LMS per streaming locale"
version: "1.1.0"
slug: "alexa_audio_bridge"
url: "https://github.com/Dregi56/repository-alexa-audio"
image: "lmscommunity/logitechmediaserver"
arch:
  - amd64
  - aarch64
startup: services
boot: auto
host_network: true


