name: "Alexa Audio Bridge"
description: "Streaming audio locale per Alexa tramite LMS (Lyrion)"
version: "1.0.2"
slug: "alexa_audio_bridge"
url: "https://github.com/Dregi56/repository-alexa-audio"
author: "Egidio Ziggiotto"
maintainer: "Egidio Ziggiotto <dregi@cyberservices.com>"
startup: services
boot: auto
init: false
host_network: true
map:
  - config:rw
  - media:ro
options:
  log_level: info
schema:
  log_level: "list(trace|debug|info|notice|warning|error|fatal)"
