name: "Alexa Audio Bridge"
version: "1.0.0"
slug: "alexa_audio_bridge"
url: "https://github.com/Dregi56/repository-alexa-audio"
description: "Simula una radio streaming per Alexa usando file locali"
arch:
  - amd64
  - armv7
  - arm64
startup: services
boot: auto
ports:
  8000/tcp: 8000
map:
  - media:rw
options: {}
schema: {}


